# Generated by Django 5.2.2 on 2025-06-09 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filme", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filme",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("Copa do Brasil", "Copa do Brasil"),
                    ("Libertadores", "Libertadores"),
                    ("Campeonato Estadual", "Campeonato Estadual"),
                ],
                default="Outros",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="filme",
            name="data_criacao",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="filme",
            name="thumb",
            field=models.ImageField(blank=True, null=True, upload_to="thumb_filmes"),
        ),
        migrations.AddField(
            model_name="filme",
            name="visualizacoes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="filme",
            name="titulo",
            field=models.CharField(max_length=100),
        ),
    ]
