# Generated by Django 5.2.2 on 2025-06-12 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filme", "0002_filme_categoria_filme_data_criacao_filme_thumb_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filme",
            name="ano",
            field=models.IntegerField(
                choices=[
                    (2000, "2000"),
                    (2001, "2001"),
                    (2002, "2002"),
                    (2003, "2003"),
                    (2004, "2004"),
                    (2005, "2005"),
                    (2006, "2006"),
                    (2007, "2007"),
                    (2008, "2008"),
                    (2009, "2009"),
                    (2010, "2010"),
                    (2011, "2011"),
                    (2012, "2012"),
                    (2013, "2013"),
                    (2014, "2014"),
                    (2015, "2015"),
                    (2016, "2016"),
                    (2017, "2017"),
                    (2018, "2018"),
                    (2019, "2019"),
                    (2020, "2020"),
                    (2021, "2021"),
                    (2022, "2022"),
                    (2023, "2023"),
                    (2024, "2024"),
                    (2025, "2025"),
                ],
                default=2024,
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2025),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="filme",
            name="thumb",
            field=models.ImageField(upload_to="thumb_filmes"),
        ),
    ]
