# Generated by Django 5.2.2 on 2025-06-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filme", "0003_filme_ano_alter_filme_thumb"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filme",
            name="ano",
        ),
    ]
