# Generated by Django 5.2.2 on 2025-06-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filme", "0006_episodio"),
    ]

    operations = [
        migrations.AddField(
            model_name="filme",
            name="campeao",
            field=models.BooleanField(default=False),
        ),
    ]
