# Generated by Django 5.2.2 on 2025-06-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filme", "0007_filme_campeao"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodio",
            name="descricao",
            field=models.TextField(
                default="Uma vez Flamengo Sempre Flamengo", max_length=1000
            ),
            preserve_default=False,
        ),
    ]
