# Generated by Django 5.2.2 on 2025-06-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filme", "0008_episodio_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodio",
            name="thumb",
            field=models.ImageField(blank=True, null=True, upload_to="thumb_episodios"),
        ),
    ]
