# Generated by Django 5.2.2 on 2025-06-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filme", "0009_episodio_thumb"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodio",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AlterField(
            model_name="filme",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("Copa do Brasil", "Copa do Brasil"),
                    ("Libertadores", "Libertadores"),
                    ("Campeonato Estadual", "Campeonato Estadual"),
                    ("Copa do Mundo de Clubes", "Copa do Mundo de Clubes"),
                ],
                default="Outros",
                max_length=50,
            ),
        ),
    ]
