# Generated by Django 5.2.2 on 2025-06-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filme", "0010_episodio_video_alter_filme_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodio",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("Fase de Grupos", "Fase de Grupos"),
                    ("Oitavas de Final", "Oitavas de Final"),
                    ("Quartas de Final", "Quartas de Final"),
                    ("Semifinal", "Semifinal"),
                    ("Final", "Final"),
                ],
                default="Outros",
                max_length=50,
            ),
        ),
    ]
