# Generated by Django 5.2.2 on 2025-06-22 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filme", "0011_episodio_categoria"),
    ]

    operations = [
        migrations.RenameField(
            model_name="episodio",
            old_name="categoria",
            new_name="fases",
        ),
    ]
