# Generated by Django 5.2.2 on 2025-06-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filme", "0012_rename_categoria_episodio_fases"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodio",
            name="visualizacoes",
            field=models.IntegerField(default=0),
        ),
    ]
