# Generated by Django 5.2.1 on 2025-06-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0013_episodio_visualizacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='curtidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='episodio',
            name='deslikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='episodio',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
