# Generated by Django 5.2 on 2025-06-25 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0014_episodio_curtidas_episodio_deslikes_episodio_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='usuarios_que_curtiram',
            field=models.ManyToManyField(blank=True, related_name='episodios_curtidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
