# Generated by Django 5.2 on 2025-06-25 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0015_filme_usuarios_que_curtiram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodio',
            name='curtidas',
        ),
        migrations.RemoveField(
            model_name='episodio',
            name='deslikes',
        ),
        migrations.RemoveField(
            model_name='episodio',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='usuarios_que_curtiram',
        ),
        migrations.AddField(
            model_name='episodio',
            name='usuarios_que_curtiram',
            field=models.ManyToManyField(blank=True, related_name='episodios_curtidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
