# Generated by Django 5.2 on 2025-06-25 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0016_remove_episodio_curtidas_remove_episodio_deslikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='usuarios_deslikes',
            field=models.ManyToManyField(blank=True, related_name='episodios_deslike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='episodio',
            name='usuarios_que_amaram',
            field=models.ManyToManyField(blank=True, related_name='episodios_amados', to=settings.AUTH_USER_MODEL),
        ),
    ]
