# Generated by Django 5.2 on 2025-06-25 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0018_alter_episodio_usuarios_deslikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodio',
            old_name='usuarios_deslikes',
            new_name='usuarios_dislikes',
        ),
    ]
