# Generated by Django 5.2.1 on 2025-06-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0019_rename_usuarios_deslikes_episodio_usuarios_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='filmes_favoritos',
            field=models.ManyToManyField(related_name='usuarios_que_favoritaram', to='filme.filme'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='filmes_vistos',
            field=models.ManyToManyField(related_name='usuarios_que_viram', to='filme.filme'),
        ),
    ]
