# Generated by Django 5.2 on 2025-06-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0020_usuario_filmes_favoritos_alter_usuario_filmes_vistos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='filmes_favoritos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='episodios_favoritos',
            field=models.ManyToManyField(related_name='usuarios_que_favoritaram', to='filme.episodio'),
        ),
    ]
